### ISSUE TITLE
Support for `--test-target` option when running tests

### ISSUE THREAD

**Issue by dlethin** [piotrmadry/FirebaseTestLab-Android#11]
First off, fantastic plugin.  This was incredibly help in jumpstarting our use of Firebase Test Lab.  Thank so much for sharing it.

Any chance of adding support to allow us us to specify which tests we want to run -- Ideally on the commmand line?

This seems to be possible through the gcloud binary according to the doc:

```
gcloud firebase test android run --help
...

ANDROID INSTRUMENTATION TEST FLAGS
...
     --test-targets=TEST_TARGET,[TEST_TARGET,...]
        A list of one or more instrumentation test targets to be run (default:
        all targets). Each target must be fully qualified with the package name
        or class name, in one of these formats:
        ◆ "package package_name"
        ◆ "class package_name.class_name"
        ◆ "class package_name.class_name#method_name".
...
```

I suppose it could be an option in your plugin configuration, and maybe picked up from some project property, similar to how you can control which tests you want to run using the `--tests` [argument](https://docs.gradle.org/current/userguide/java_testing.html) when running java tests through gradle.

I could in theory attempt to try to create a PR for this. I've written Gradle plugins before and looking at the `FirebaseTestLabProcessCreator.kt` file on how the gcloud command invokation is created, it doesn't look too bad.    I'm new to Kotjin, though, but even that doesn't look too bad.

If you have any suggestions on implementation, let me know.

Thanks.

Doug

**Comment by dlethin** [comment]
Thanks. There was also a question of whether or not we could benefit having the plugin support the ability to set `--test-package` option.   I can't say I understand the subtle differences between all the the "ANDROID INSTRUMENTATION TEST FLAGS" documented [here](https://cloud.google.com/sdk/gcloud/reference/firebase/test/android/run).

**Comment by jacek-marchwicki** [comment]
I think `--test-package` option is not required because of its read from test's `AndroidManifest.xml` (because tests are bundled to separate APK with different package name than your application APK).

Maybe if someone will find situation where this value should be useful we can add such feature later

**Comment by himasimplisafe** [comment]
Can you get this project property and add it to command for us so that we can use below? 
./gradle test -Dfirebase.test.lab.target=package com.example.some,class com.example.ClassName.

Context on why we need this: We currently have Local unit tests, Instrumentation tests and UI tests. We are thinking to run particular set of tests, not all.
Thanks

**Comment by dlethin** [comment]
So, I finally found a little time to take a first pass at coding this enhancement to your plugin.  Took a bit longer since I don't know kotlin, but I'm pretty proficient with gradle and writing custom plugins so I just forced my way through it.

I am now able to pass `-Pfirebase.test.lab.targets="package com.simplisafe.mobile.InstrumentedUnitTest"`  ( I'll change that to be a -D sysprop if that is preferred) and I can see in the firebase console that my argument is being passed.

However we did observe a strange behavior where other packages get run in addition to the one we wanted to exclusively run, although not all classes with those extra packages get run.  Weird.

As an experiment, we ran the gradle passing `-Pfirebase.test.lab.targets="class com.simplisafe.mobile.InstrumentedUnitTest.AlertsUnitTest"` to limit tests to a specific class only, and that worked fine.

I have no experience with Firebase Test Lab prior to this -- I'm not an android developer (beyond writting a HelloWorld app once). I'm just offering my gradle experience to some colleagues that were looking for this feature in your plugin.  It seems we've got the gradle mechanics in place to pass this extra argument through your plugin to firebase test lab, but its not actually having the outcome we are expecting.

Have you ever observed this or have suggestions on how to troubleshoot. We might have to figure out how to file an issue with the gcloud developers or firebase.  I'm hesitant to proceed with submitting a PR to you for this functionality until we validate its working.  

Thanks.

**Comment by jacek-marchwicki** [comment]
Unfruntelly I wouldn't give you much help. We didn't use selectors for running tests on Firebase. We just run everything at once.

**Comment by jacek-marchwicki** [comment]
Now there is an option to set test targets. Look at the latest readme file (`testTargets = ["size large"]`)

**Comment by jacek-marchwicki** [comment]
@piotrmadry I think you can close the issue.
