### ISSUE TITLE
Add support for testing Android Library projects

### ISSUE THREAD

**Issue by jasonschroeder** [piotrmadry/FirebaseTestLab-Android#12]
I would love to use this for a Kotlin-based Android Library project.

My `build.gradle` sets up the project like this:
```groovy
apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: "kotlin-kapt"
```

When I try to use this plugin, I get the following error:

```bash
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':SampleLibrary'.
> com.android.build.gradle.LibraryExtension_Decorated cannot be cast to com.android.build.gradle.AppExtension
```
Which seems to point to the cast here: https://github.com/piotrmadry/FirebaseTestLab-Android/blob/d684981b6f2d57e4f61a96134d9f7844657070cf/plugin/src/main/java/com/appunite/firebasetestlabplugin/FirebaseTestLabPlugin.kt#L195

Would you consider adding support for an Android Library project? 
Thank you!

**Comment by jacek-marchwicki** [comment]
Thank you for your report! Unfortunately, we don't have plans to implement support for libraries.
If you have time we would be happy to accept pull-requests.

**Comment by jasonschroeder** [comment]
Thanks for the prompt reply. I will need to work on my Kotlin skills first :) Please leave this ticket open for a little bit? Thanks again.
