### ISSUE TITLE
Download results without running robo tests

### ISSUE THREAD

**Issue by johnfrey99** [piotrmadry/FirebaseTestLab-Android#16]
Would be nice if there was a way to run the `firebaseTestLabDownload` task without running the robo tests.

**Comment by piotrmadry** [comment]
If you want to run instrumentation tests only you can use `firebaseTestLabExecute*BuildType*Instrumentation`

**Comment by zbynek** [comment]
You can now also execute + download the tests using
`firebaseTestLabDownload*Variant*Instrumentation`
where variant is either e.g. `Debug` or `FlavorDebug` if you use flavors.
