### ISSUE TITLE
Sample usage with kotlin-dsl

### ISSUE THREAD

**Issue by giangpham96** [piotrmadry/FirebaseTestLab-Android#18]
Hi there,

I have a project using kotlin dsl. Can you give an example with kotlin instead of groovy? Thanks in advance.
I am having trouble with configuring the `devices` function of `FirebaseTestLabPluginExtension`

**Comment by piotrmadry** [comment]
@giangpham96 What kind of troubles do you have? Can you share more details?

**Comment by giangpham96** [comment]
So the devices function requires a Closure object as a parameter. I tried using `closureOf<Device>{...}` and `delegateClosureOf<Device>{...}`, but during compile time, I got NPE. I will share the stacktrace later as I don't have access to the project currently

**Comment by zbynek** [comment]
It works with createDevice
```
firebaseTestLab {
    keyFile = file("test-lab-key.json")
    googleProjectId = "your-project-app-id"
    createDevice("nexusEmulator") {
        deviceIds = listOf("hammerhead")
        androidApiLevels = listOf(23)
    }
    createDevice("nexusEmulator2") {
        deviceIds = listOf("hammerhead")
        androidApiLevels = listOf(23)
    }
}
```

**Comment by piotrmadry** [comment]
@giangpham96 Does it work for you?

**Comment by giangpham96** [comment]
@piotrmadry I will try asap. I will close the issue now and reopen if needed
