### ISSUE TITLE
Timeout variable not recognized by gcloud

### ISSUE THREAD

**Issue by ronaldvanduren** [piotrmadry/FirebaseTestLab-Android#21]
When using the following block:
devices {
        someOtherDevices {
            deviceIds = ["Pixel2"]
            androidApiLevels = [28]
            isUseOrchestrator = true
            locales = ["en_GB"]
            timeout = 3600
        }
    }

The timeout variable is not recognized by gcloud and this results in the following error: 
ERROR: (gcloud.firebase.test.android.run) unrecognized arguments: --timeoutSec=3600s (did you mean '--timeout'?)

**Comment by piotrmadry** [comment]
Fixed in version 2.0.0 @ronaldvanduren
